
let allHotels = [
    {
        id : 1,
        city : 'coxbazar',
        hotelName : 'Long Beach',
        ratings : 9.2,
        price : 1300,
        beds : ['Single Bed','Double Bed','Family Suit','Vip'],
        freeWifi : 'yes',
        freeParking : 'yes',
        airportShuttle : 'yes',
        restaurant : 'yes',
        bar : 'yes',
        swimmingPool : 'Yes',
        beachFront : 'yes',
        stars : 4,
        fitnessCenter: 'yes',
        thumbImg : 'https://i.ibb.co/dPgCvny/long-beach.jpg'
    },
    {
        id : 2,
        city : 'coxbazar',
        hotelName : 'Hotel Sea Crown',
        ratings : 7.2,
        price : 600,
        beds : ['Single Bed','Double Bed','Family Suit','Vip'],
        freeWifi : 'yes',
        freeParking : 'yes',
        airportShuttle : 'yes',
        restaurant : 'yes',
        bar : 'yes',
        swimmingPool : 'no',
        beachFront : 'yes',
        stars : 3,
        fitnessCenter: 'no',
        thumbImg : 'https://i.ibb.co/yYc2MQs/sea-crown.jpg'
    },
    {
        id : 3,
        city : 'coxbazar',
        hotelName : 'Hotel Sea Shine',
        ratings : 6.2,
        price : 300,
        beds : ['Single Bed','Double Bed','Family Suit','Vip'],
        freeWifi : 'yes',
        freeParking : 'yes',
        airportShuttle : 'yes',
        restaurant : 'yes',
        bar : 'yes',
        swimmingPool : 'no',
        beachFront : 'no',
        stars : 0,
        fitnessCenter: 'no',
        thumbImg : 'https://i.ibb.co/PNkMDGn/sea-shine.jpg'
    },
    {
        id : 4,
        city : 'Dhaka',
        hotelName : 'Hotel Dhaka',
        ratings : 6.2,
        price : 300,
        beds : ['Single Bed','Double Bed','Family Suit','Vip'],
        freeWifi : 'yes',
        freeParking : 'yes',
        airportShuttle : 'yes',
        restaurant : 'yes',
        bar : 'yes',
        swimmingPool : 'no',
        beachFront : 'no',
        stars : 0,
        fitnessCenter: 'no',
        thumbImg : 'https://i.ibb.co/PNkMDGn/sea-shine.jpg'
    }
]