
let allHotels = [
    {
        id : 1,
        city : 'coxbazar',
        hotelName : 'Long Beach',
        ratings : 9.2,
        price : 1300,
        beds : ['Single Bed','Double Bed','Family Suit','Vip'],
        freeWifi : 'yes',
        freeParking : 'yes',
        airportShuttle : 'yes',
        restaurant : 'yes',
        bar : 'yes',
        swimmingPool : 'Yes',
        beachFront : 'yes',
        stars : 4,
        fitnessCenter: 'yes',
        thumbImg : 'https://i.ibb.co/WK2LjKn/long-beach.jpg'
    },
    {
        id : 2,
        city : 'coxbazar',
        hotelName : 'Hotel Sea Crown',
        ratings : 7.2,
        price : 600,
        beds : ['Single Bed','Double Bed','Family Suit','Vip'],
        freeWifi : 'yes',
        freeParking : 'yes',
        airportShuttle : 'yes',
        restaurant : 'yes',
        bar : 'yes',
        swimmingPool : 'no',
        beachFront : 'yes',
        stars : 3,
        fitnessCenter: 'no',
        thumbImg : 'https://i.ibb.co/yYc2MQs/sea-crown.jpg'
    },
    {
        id : 3,
        city : 'coxbazar',
        hotelName : 'Hotel Sea Shine',
        ratings : 6.2,
        price : 300,
        beds : ['Single Bed','Double Bed','Family Suit','Vip'],
        freeWifi : 'yes',
        freeParking : 'yes',
        airportShuttle : 'yes',
        restaurant : 'yes',
        bar : 'yes',
        swimmingPool : 'no',
        beachFront : 'no',
        stars : 0,
        fitnessCenter: 'no',
        thumbImg : 'https://i.ibb.co/PNkMDGn/sea-shine.jpg'
    },
    {
        id : 4,
        city : 'dhaka',
        hotelName : 'Hotel Dhaka',
        ratings : 6.2,
        price : 300,
        beds : ['Single Bed','Double Bed','Family Suit','Vip'],
        freeWifi : 'yes',
        freeParking : 'yes',
        airportShuttle : 'yes',
        restaurant : 'yes',
        bar : 'yes',
        swimmingPool : 'no',
        beachFront : 'no',
        stars : 0,
        fitnessCenter: 'no',
        thumbImg : 'https://i.ibb.co/PNkMDGn/sea-shine.jpg'
    },
    {
        id : 4,
        city : 'dhaka',
        hotelName : 'Hotel Dhaka',
        ratings : 6.2,
        price : 300,
        beds : ['Single Bed','Double Bed','Family Suit','Vip'],
        freeWifi : 'yes',
        freeParking : 'yes',
        airportShuttle : 'yes',
        restaurant : 'yes',
        bar : 'yes',
        swimmingPool : 'no',
        beachFront : 'no',
        stars : 0,
        fitnessCenter: 'no',
        thumbImg : 'https://i.ibb.co/PNkMDGn/sea-shine.jpg'
    },
    {
        id : 5,
        city : 'ctg',
        hotelName : 'Hotel Agrabad',
        ratings : 7.2,
        price : 900,
        beds : ['Single Bed','Double Bed','Family Suit','Vip'],
        freeWifi : 'yes',
        freeParking : 'yes',
        airportShuttle : 'yes',
        restaurant : 'yes',
        bar : 'yes',
        swimmingPool : 'yes',
        beachFront : 'no',
        stars : 4,
        fitnessCenter: 'yes',
        thumbImg : 'https://i.ibb.co/2yxjfqy/hotel-agrabad-ctg.jpg'
    },
    {
        id : 5,
        city : 'ctg',
        hotelName : 'Radison Blue',
        ratings : 9.2,
        price : 1300,
        beds : ['Single Bed','Double Bed','Family Suit','Vip'],
        freeWifi : 'yes',
        freeParking : 'yes',
        airportShuttle : 'yes',
        restaurant : 'yes',
        bar : 'yes',
        swimmingPool : 'yes',
        beachFront : 'yes',
        stars : 5,
        fitnessCenter: 'yes',
        thumbImg : 'https://i.ibb.co/1937C52/well-park-ctg.jpg'
    },
    {
        id : 6,
        city : 'ctg',
        hotelName : 'Well Park',
        ratings : 6.2,
        price : 700,
        beds : ['Single Bed','Double Bed','Family Suit','Vip'],
        freeWifi : 'yes',
        freeParking : 'no',
        airportShuttle : 'no',
        restaurant : 'yes',
        bar : 'yes',
        swimmingPool : 'no',
        beachFront : 'no',
        stars : 3,
        fitnessCenter: 'no',
        thumbImg : 'https://i.ibb.co/1937C52/well-park-ctg.jpg'
    },
]